### ISSUE TITLE
Test strategy

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt-cloud/cdt-gdb-adapter#12]
Time to put together a test strategy for the adapter. We want to be able to confidently make changes without breaking the clients.

We have experience with mocha but I hear that it doesn't have good Jenkins reporting which we need for the CI machine.

Anyone else have any ideas?

**Comment by dschaefer** [comment]
There's probably two levels of testing here. Unit and integration. Unit tests the APIs of the components, where integration would actually test against a running gdb and fake out a client.

**Comment by simark** [comment]
For the integration test using a fake client, this seems nice, part of the vscode-debugadapter repo:

https://github.com/Microsoft/vscode-debugadapter-node/tree/master/testSupport

I am planning to start writing some tests with it, any objections?

What kind of test output does your Jenkins job want?  It is possible to write new reporters for mocha, so I assume it's possible to output what you need.

For the unit tests, mocha + chai is a combo that works well, that's what we use in Theia.

**Comment by dschaefer** [comment]
> For the integration test using a fake client, this seems nice, part of the vscode-debugadapter repo:
> 
> https://github.com/Microsoft/vscode-debugadapter-node/tree/master/testSupport
> 
> I am planning to start writing some tests with it, any objections?

That would be awesome! Go ahead.

> 
> What kind of test output does your Jenkins job want? It is possible to write new reporters for mocha, so I assume it's possible to output what you need.
> 
> For the unit tests, mocha + chai is a combo that works well, that's what we use in Theia.

Yeah, that's what we use for our web projects here at QNX. The biggest issue we've had is with finding good reporters that present the results nicely. I'll have to see what the current state of all that is.

**Comment by dschaefer** [comment]
Actually we have a reporter we're using internally. I should be able to open it.

**Comment by dschaefer** [comment]
We have the integration story in place. Thanks @simark!
Be good to have a unit test strategy where we mock out gdb as well.

**Comment by jonahgraham** [comment]
@thegecko Please comment here and I will try to figure it out.

**Comment by jonahgraham** [comment]
In #136 @thegecko mentions issues with MacOS. I didn't know that tests didn't work on MacOS. I am in the process of bringing up a machine to add to the CI to regtest on Windows, but I don't have any immediate plans on Mac - but I could do the same there at some point. 

@thegecko the best would be that tests "just worked" on Mac. What is the issue there? Is it the getting a GDB/GCC/toolchain that works easily, or something else?

**Comment by thegecko** [comment]
I see lots of gdb errors, so it's likely that needs to be configured properly. e.g.

```
Uncaught Error: spawn gdbserver ENOENT

Error: Unable to find Mach task port for process-id 58698: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))

Error: gdbserver has hit error Error: spawn gdbserver ENOENT
```

I wonder if a docker container would make sense to encapsulate the test environment?

**Comment by jonahgraham** [comment]
> I wonder if a docker container would make sense to encapsulate the test environment?

There is already one based on cdt-infra, you can do something like this if you are in the root of the project. (Or just run bash in the container and do things manually)

```
docker run --rm -it -v $PWD:/work -w /work  quay.io/eclipse-cdt/cdt-infra-eclipse-full:ubuntu-16.04-a6ea855 /bin/bash -c 'yarn install && yarn build && yarn test'
```

For ease of use a "latest" tag would probably make sense - perhaps also one that does not start UI/VNC environment.

**Comment by simark** [comment]
The state of GDB on macOS isn't so great, so there is probably nothing else to do other than fix GDB itself.

**Comment by thegecko** [comment]
@jonahgraham I see you updated instructions in #144 

On my machine this errors unfortunately:

```
Robs-iMac:cdt-gdb-adapter thegecko$ docker run --rm -it -v $(git rev-parse --show-toplevel):/work -w /work/$(git rev-parse --show-prefix) --cap-add=SYS_PTRACE --security-opt seccomp=unconfined quay.io/eclipse-cdt/cdt-infra-eclipse-full:latest yarn test
Unable to find image 'quay.io/eclipse-cdt/cdt-infra-eclipse-full:latest' locally
latest: Pulling from eclipse-cdt/cdt-infra-eclipse-full
5667fdb72017: Pull complete 
d83811f270d5: Pull complete 
ee671aafb583: Pull complete 
7fc152dfb3a6: Pull complete 
eeb59844c88b: Pull complete 
f43df22e4711: Pull complete 
d07816dc3ca8: Pull complete 
e9fccb9b0829: Pull complete 
a004456d8e7b: Pull complete 
4d6366bbe6a4: Pull complete 
458bfadf248e: Pull complete 
257e47fc66b2: Pull complete 
27457488a691: Pull complete 
4161bba5b45e: Pull complete 
6ed5400d93c5: Pull complete 
e8fb540c4f6c: Pull complete 
513ebb995671: Pull complete 
aa2458f1d031: Pull complete 
ec88e9f7f81d: Pull complete 
e01b96631b9f: Pull complete 
0bb7b11f7d58: Pull complete 
6b4ad39fb5ee: Pull complete 
2a422eb69cc2: Pull complete 
0dde373ae04b: Pull complete 
450ca14a3dbf: Pull complete 
bad1ea8640db: Pull complete 
f56a5e03017c: Pull complete 
b83b56f4437f: Pull complete 
e9d995492e40: Pull complete 
3e5a80d8f1bf: Pull complete 
Digest: sha256:c7409b802f7d70c936bd851efee25951e548d935615cb2b7f5959bc3aab2f9cc
Status: Downloaded newer image for quay.io/eclipse-cdt/cdt-infra-eclipse-full:latest
whoami: cannot find name for user ID 1000
yarn run v1.19.1
$ yarn test:integration && yarn test:pty && yarn test:integration-run-in-terminal && yarn test:integration-remote-target && yarn test:integration-remote-target-run-in-terminal
$ cross-env JUNIT_REPORT_PATH=test-reports/integration.xml JUNIT_REPORT_STACK=1 JUNIT_REPORT_PACKAGES=1 mocha --reporter mocha-jenkins-reporter dist/integration-tests/*.spec.js
/bin/sh: 1: cross-env: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jonahgraham** [comment]
I think you need to do the yarn install & yarn build first for the container, cross-env comes in there.

**Comment by thegecko** [comment]
> you need to do the yarn install & yarn build first

Yup, that fixed the run.

Unfortunately 8 of the 19 tests failed :(

**Comment by jonahgraham** [comment]
Does qemu work on Macos? Because so much of the focus is on embedded dev, I thought it would be good if we had a "true" cross platform / remote dev environment. That may be easier?

**Comment by jonahgraham** [comment]
I suspect that the 8 out of 19 failed is because the elf files were not rebuilt in the container? I can reproduce something similar. I have [added](https://github.com/eclipse-cdt/cdt-gdb-adapter/tree/master/src/integration-tests#error-no-source-file-name-work) to the documentation on running tests to say that you should be fully clean when changing platforms (the change is implicit when going from host to container run).

**Comment by jonahgraham** [comment]
See PR #146

**Comment by jonahgraham** [comment]
We have fairly decent tests now - some more work to be done in #160
