### ISSUE TITLE
Support integrated terminal

### ISSUE THREAD

**Issue by a1994846931931** [eclipse-cdt-cloud/cdt-gdb-adapter#151]
It's of vital importance that the integrated terminal is supported because many c/c++ programs rely on standard input in which case it's impossible to debug through internal debug console.

Do we have any plans for this?

**Comment by marechal-p** [comment]
Set `"openGdbConsole": true` in your launch configuration, it should open a second GDB interface inside an integrated terminal in your IDE. Unix only.

**Comment by a1994846931931** [comment]
> Set `"openGdbConsole": true` in your launch configuration, it should open a second GDB interface inside an integrated terminal in your IDE. Unix only.

@marechal-p Have you tried this on program with standard input like `std::cin`? It shows me `../sysdeps/unix/sysv/linux/read.c: No such file or directory.` error.

Besides, I don't think it's a good idea to open a gdb interface to use. It requires knowledge of gdb and, for many, it's hard to use.

Can't we launch integrated terminal when `console` is set to `integratedTerminal` or `externalTerminal` like most VSCode's extension do? For example, in VSCode's python extension:
https://github.com/microsoft/vscode-python/blob/55281bc1f643cb7c2ee1df70323636d6321cecf6/src/client/debugger/debugAdapter/DebugClients/LocalDebugClient.ts#L79-L84

Which leads to
https://github.com/microsoft/vscode-python/blob/55281bc1f643cb7c2ee1df70323636d6321cecf6/src/client/debugger/debugAdapter/DebugClients/LocalDebugClient.ts#L156

**Comment by marechal-p** [comment]
My bad, I misunderstood. So running the inferior into an actual terminal displayed in the IDE, good idea!

**Comment by jonahgraham** [comment]
This is essentially the same request as #161 - closing this copy as #161 has more details.
