### ISSUE TITLE
Minimum supported GDB version

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt-cloud/cdt-gdb-adapter#159]
@thegecko @marechal-p @jcrwilliams  @jjohnstn @Kummallinen @jld01

I have some fixes pending for #152, but it means changing the minimum version supported of GDB to 7.11. In fact, the function breakpoint support that is already in already requires GDB 7.11 as a minimum version - but if needed we can back it out/redo it.

I have cc'ed you all as the knows adopters or because I hope you can provide an opinion. Do you have an opinion on the minimum version of GDB we should support?

Note this has been discussed in other forms before, see for example open issue #92. However I don't want to add infra in yet for supporting multiple versions. Indeed in #92 the simplification would be just to support 7.12+.

As this is a fairly new project I don't want to spend a lot of time supporting old GDBs that no one is actually using - or at least defer support for them until there is a genuine need.

**Comment by thegecko** [comment]
Thanks for raising this and apologies for bringing in a feature which upped the minimum version. We use 7.12, so would be fine with supporting that version and newer.

**Comment by jonahgraham** [comment]
See #160 for test coverage on what we support so that we can introduce new features without breaking platforms we are not on.

**Comment by marcdumais-work** [comment]
@jonahgraham We checked internally and it looks ok for us as well to go with 7.12+.

**Comment by jonahgraham** [comment]
Since this issue was raised we had to add support to older versions of GDB, e.g. #188
