### ISSUE TITLE
How to use the logging?

### ISSUE THREAD

**Issue by simark** [eclipse-cdt-cloud/cdt-gdb-adapter#19]
I noticed that we inherit from `LoggingDebugSession`, but with the existing code, I couldn't get logging to work.  I could get it by tweaking a few things.  Before proposing a change, I was wondering if it's just because I am doing it wrong.  Is there a way to get logging to work with the current code?

**Comment by dschaefer** [comment]
Did you turn verbose: true in the launch args?

**Comment by simark** [comment]
Yes I did.

I think one of the problems is that the log file must be absolute?

https://github.com/Microsoft/vscode-debugadapter-node/blob/master/adapter/src/logger.ts#L168

**Comment by dschaefer** [comment]
Could be. We don't use the log file since vscode just prints the messages on the Debug Output console.

**Comment by simark** [comment]
Ok.  To have more control over our logging, I would lean towards not using `LoggingDebugSession` and do our own logging using a specialized library, like [winston](https://github.com/winstonjs/winston).

**Comment by jonahgraham** [comment]
PRs that improve or change this more than welcome, but for now the logging is working. Since this request came up, some significant work was done to save logs during all test runs, so if there is a change here in the future that functionality should be kept.
