### ISSUE TITLE
Make use of cdt-gdb-adapter along with cdt-gdb-vscode

### ISSUE THREAD

**Issue by santimchp** [eclipse-cdt-cloud/cdt-gdb-adapter#229]
We have installed "**cdt-gdb-vscode**" extension into Eclipse Theia in order to debug RiscV implementations, and for this to open a debug session and  work properly we had installed  "**ms-vscode,cpptools**" for "C/C++" tooling, and it was working fine, but as everybody knows the problem is that we can't use it due to Microsoft license restrictions.

So as an alternative we came across CDT GDB Debug Adapter (**cdt-gdb-adapter**) from Stefan Dirix on the TheiaCon presentations, which we think it might be the solution to enable our already installed "**cdt-gdb-vscode**" extension and replace the  "**ms-vscode,cpptools**", so we were wondering how to make use of it, and how to integrate it. We were watching and reading the documentation available and we are still a bit confused, as it is not in a shape of an extension that you can just install from VSIX straight away.

Thank you

**Comment by jonahgraham** [comment]
cc: @sdirix may be able to help on getting it into theia.

Have a look at what [cdt cloud blueprint](https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/blob/b88fdc9b9ca3bd4282a5337e63f5b1e607275277/applications/electron/package.json#L141) does to pull it in. It uses the build that is published to [open vsx](https://open-vsx.org/extension/eclipse-cdt/cdt-gdb-vscode)

**Comment by jonahgraham** [comment]
I hope you got the answers you were looking for. If you need more, please reopen the question.
