### ISSUE TITLE
Memory View

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt-cloud/cdt-gdb-adapter#27]
Add the ability to fetch blocks of memory using the data-read-memory MI command and friends.

Create React components to show the user the results. We can use these view components in both VS Code and Theia. If we ever figure out how to get a good browser in the Eclipse IDE, we can use it there too.

**Comment by simark** [comment]
I am planning to work on the adapter bits to read memory very soon (probably this week).

**Comment by dschaefer** [comment]
Very cool. Thanks Simon!

**Comment by dschaefer** [comment]
BTW, is your work on this with Theia somewhere in the open? I'd like to see how hard it would be to provide a UI for this that works with both Theia and vscode.

**Comment by mikhailkhod** [comment]
There is no specifications regarding memory fetching for DAP (https://microsoft.github.io/debug-adapter-protocol/specification). I assume, defining it is a part of the task. Is this correct?
Just for clarification, "data-read-memory" command is deprecated. We use "data-read-memory-bytes" in CDT.

**Comment by simark** [comment]
> There is no specifications regarding memory fetching for DAP (https://microsoft.github.io/debug-adapter-protocol/specification). I assume, defining it is a part of the task. Is this correct?

Exact.

> Just for clarification, "data-read-memory" command is deprecated. We use "data-read-memory-bytes" in CDT.

Exact.

**Comment by simark** [comment]
> BTW, is your work on this with Theia somewhere in the open? I'd like to see how hard it would be to provide a UI for this that works with both Theia and vscode.

It's still just a local draft, but in the following days weeks, I should have a PR on Theia to start using this adapter instead of code-debug.

**Comment by simark** [comment]
I have something basic but working on this branch:

https://github.com/simark/cdt-gdb-adapter/tree/simark/zoe_chartrand

I'll wait until I can try it in an actual IDE before submitting it, to see if the request/response formats make sense.

**Comment by dschaefer** [comment]
Cool. Looks good so far. I'll start thinking about how we'd do this in code. My current thinking is to create a simple command that prompts for the start address and length and opens up a webview with a simple dump of the result. Not sure yet how to get a handle on the debug client tho.

**Comment by jonahgraham** [comment]
Might be worth looking at https://github.com/jonahgraham/cortex-debug which does roughly what you have outlined (for disassembly too)

**Comment by dschaefer** [comment]
Thanks Jonah. There's also the PlatformIO IDE that has something similar. It would be great to standardize on something and have these IDEs use it so we don't have umpteen Register views etc. :).

Anyway, we can have more in depth vscode discussions here https://github.com/eclipse-cdt/cdt-gdb-vscode/issues/8

**Comment by dschaefer** [comment]
BTW, as we think about the IDE side of this, it brings up the other side of this issue, a reusable UI component for rendering the result that can be used by Theia and VSCode and any other IDE that uses HTML UI, even the Eclipse IDE in a browser widget if we could ever get that reliable.

Where should we host that though? Here? or a new github repo.

**Comment by dschaefer** [comment]
Removed the help wanted label since we have people working on this.

**Comment by jonahgraham** [comment]
This is very out of date now, memory access is part of the DAP protocol, and the excellent memory inspector from Theia is being ported to VSCode too - https://github.com/eclipse-cdt-cloud/vscode-memory-inspector
