### ISSUE TITLE
Dose not support chinese character? 

### ISSUE THREAD

**Issue by wss29** [eclipse-cdt-cloud/cdt-gdb-adapter#275]
Hi,
   I have a simple C++ file, and I want to debug it in vscode, the path of the C++ file has some Chinese characters, and when I debug I get an error
![image](https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/assets/4537809/0e87ce64-83f8-42a9-9205-6bb83a4d1713)
my project folder is as follows
![image](https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/assets/4537809/dc84fc3e-7882-4530-8e63-af73dc67260f)
It seems that cdt-gdb-vscode does not recognize ‘测试’, and give a series of number which is not in my project
when I change ‘测试’ to English character it is ok… . how to fix it?

**Comment by jonahgraham** [comment]
I have started with #276 which is a test that demonstrates the problem. I'm working on a fix next.
