### ISSUE TITLE
Add API to easily pause target and wait for it to be ready

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt-cloud/cdt-gdb-adapter#295]
There are a couple of places in the code where we wait for target to be suspended after issuing pause to ensure that we are operating on a suspended target. However those current places (such as use of [`waitPauseNeeded`](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/250881c64415e076d3b66068a3c7057ab9a3130f/src/GDBDebugSession.ts#L474-L492)) are not very conducive for new places, such as what is needed by #292 

This is an API feature request to add such support in a generic manner.

**Comment by Luke-zhang-mchp** [comment]
Hi @jonahgraham, I'd like to take up this issue. After looking around, I'm thinking I can just add a method in `GDBDebugSessionBase` that waits for the pause. I'll submit a draft PR soon, let me know what you think.

**Comment by jonahgraham** [comment]
@Luke-zhang-mchp that sounds great. Let me know if you have any questions as you implement this.

**Comment by jonahgraham** [comment]
We have a nice new API now for pausing/resuming (if necessary) so that operations that require a paused target can operate properly. Thanks @Luke-zhang-mchp  for picking this up.

See [GDBDebugSessionBase.pauseIfNeeded](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/6ba0de8e466f4953501181f53ecdfb14c7988973/src/gdb/GDBDebugSessionBase.ts#L336)
