### ISSUE TITLE
Support "true" GDB console

### ISSUE THREAD

**Issue by simark** [eclipse-cdt-cloud/cdt-gdb-adapter#30]
Some improvements were made to CDT and GDB to allow having a proper GDB console in CDT.  We need to have a way to do this with the adapter too.

IIRC, CDT creates a PTY, spawns GDB in CLI mode using this PTY for its stdin/stdout/stderr.  But it also creates a second PTY for MI.  When spawning GDB, is passes `-ex "new-ui mi /dev/pts/<id>"` and uses this as the MI channel.

**Comment by dschaefer** [comment]
+1 :). In vscode we have the debug console working but it's the old style console that we had in Eclipse with the input line. Having a full pty like console would be awesome.

**Comment by marechal-p** [comment]
Did [this commit](https://github.com/eclipse-cdt/cdt-gdb-adapter/commit/9f8f461d75f2dd9bf3493504e3a81938e9b7de28) resolve issue?

**Comment by Noneghost** [comment]
> Some improvements were made to CDT and GDB to allow having a proper GDB console in CDT. We need to have a way to do this with the adapter too.
> 
> IIRC, CDT creates a PTY, spawns GDB in CLI mode using this PTY for its stdin/stdout/stderr. But it also creates a second PTY for MI. When spawning GDB, is passes `-ex "new-ui mi /dev/pts/<id>"` and uses this as the MI channel.

why no use DEBUG CONSOLE user input edit send gdb common?

**Comment by jonahgraham** [comment]
_Coincidentally I am going through all the old bugs to see what is relevant, this one certainly still is._

I am curious as to the current state of this. Not sure where this work was left off a few years ago. This is a very desirable feature.

> why no use DEBUG CONSOLE user input edit send gdb commands?

A full GDB console using new-ui cli where possible would give best user experience as you get 100% features of GDB at command line. As a fallback on GDB/OS where that doesn't work, using the Debug Console to do -interpreter-exec makes sense too, but the Debug console in VS Code has functionality that is somewhere between the two, e.g. it understands structured data.

**Comment by jonahgraham** [comment]
Reading through the comments on #47, especially https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/47#issuecomment-509272124 it seems like this may already be complete. I haven't really used it, so we should make sure it still works and is documented and then close this off.

**Comment by GitMensch** [comment]
I've just tried to use the debug console to enter GDB commands, is this expected to work (like it is with all other GDB frontends I've seen)?

~~~
show version
Evaluation of expression without frameId is not supported.
From client: evaluate({"expression":"show version","context":"repl"})
To client: {"seq":0,"type":"response","request_seq":9,"command":"evaluate","success":false,"body":{"result":"Error: could not evaluate expression","variablesReference":0,"error":{"id":1,"format":"Evaluation of expression without frameId is not supported.","showUser":true}},"message":"Evaluation of expression without frameId is not supported."}
~~~

**Comment by jonahgraham** [comment]
> I've just tried to use the debug console to enter GDB commands, is this expected to work (like it is with all other GDB frontends I've seen)?

No - it isn't. 

What it is supposed to do is this:

![image](https://user-images.githubusercontent.com/679236/215890538-f9e949f8-dbcf-4d5a-91d8-349ce50fce5a.png)

And there is an enhancement request for auto complete of those variables here https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/issues/75

---

What this issue covers is using new-ui to have a CLI in the terminal view. Ericsson folks have done it IIUC, but I have never tried it out. (But I am about to right now!)

**Comment by jonahgraham** [comment]
Setting `"openGdbConsole": true` in the launch.json does indeed open a terminal as [expected](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/30#issuecomment-460440625). I get the following. I think that means this issue is done. 

![image](https://user-images.githubusercontent.com/679236/215892002-4eb5017f-9656-48b5-b97d-71ddb39145aa.png)

**Comment by GitMensch** [comment]
ok, so we'd ideally have:

* debug console:
   * shows output like communication (especially when running verbose
   * option to enter expressions to be resolved (exists, seems to work)
* option to enter GDB commands (currently done via extra terminal and possibly "unix-only")
* application console for stdout and stdin (missing?)

**Comment by jonahgraham** [comment]
> * option to enter GDB commands (currently done via extra terminal and possibly "unix-only")

yes, it is unix-only, but since that code was written the work has been done on GDB side to support new-ui on Windows hosts.


> * application console for stdout and stdin (missing?)

Yes, see #161

**Comment by GitMensch** [comment]
> > * option to enter GDB commands (currently done via extra terminal and possibly "unix-only")
> 
> yes, it is unix-only, but since that code was written the work has been done on GDB side to support new-ui on Windows hosts.

Can you please link to an issue to test + handle that in cdt-gdb-adapter, too?

**Comment by jonahgraham** [comment]
> > > * option to enter GDB commands (currently done via extra terminal and possibly "unix-only")
> > 
> > 
> > yes, it is unix-only, but since that code was written the work has been done on GDB side to support new-ui on Windows hosts.
> 
> Can you please link to an issue to test + handle that in cdt-gdb-adapter, too?

#240
