### ISSUE TITLE
The "running" async record is not sending the "ContinuedEvent"

### ISSUE THREAD

**Issue by asimgunes** [eclipse-cdt-cloud/cdt-gdb-adapter#332]
Recently, we are experiencing an issue in VS Code in multi-thread debugging environment. When the program stopped in a breakpoint and all the threads stopped too, and then we continued the program, gdbserver sends the running information for all threads, however VS Code only resumes the current thread and this causes an unexpected behavior in the UI.

When we observe the logs, and review the source code, we observed that the gdb/mi async record `running` handled in `GDBDebugSessionBase` class is not sending the `ContinuedEvent` to the IDE which makes the IDE unable to receive async thread resume signals. Thus, some of the resumed threads still seen in stopped state, but they are actually in running state.

Details of the `running` record: 

* _running,thread-id="thread"_
The target is now running. The thread field can be the global thread ID of the thread that is now running, and it can be ‘all’ if all threads are running. The frontend should assume that no interaction with a running thread is possible after this notification is produced. The frontend should not assume that this notification is output only once for any command. GDB may emit this notification several times, either for different threads, because it cannot resume all threads together, or even for a single thread, if the thread must be stepped though some code before letting it run freely.

More details about the GDB/MI Async Records:
https://sourceware.org/gdb/current/onlinedocs/gdb.html/GDB_002fMI-Async-Records.html

The details of the `ContinuedEvent`
https://github.com/microsoft/vscode-debugadapter-node/blob/7b85aac40559a01b898d05638fb32f3d82cbac31/debugProtocol.json#L234

Related source code location to handle `resume` record and send the `ContinuedEvent`:
https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/89cdd9cb23d8265646734e60e6e3f0d85211fb61/src/GDBDebugSession.ts#L1788-L1802

**Comment by asimgunes** [comment]
Hi @jonahgraham ,

I created the issue details here in order to document the reason of the upcoming change, and I am planning to send an update for this issue as discussed previously. 

Could you please review the description and please feel free to add any important points.

Kind regards
Asim

**Comment by jonahgraham** [comment]
This summary looks correct to me. If gdb is resuming all threads, setting `allThreadsContinued` in `ContinuedEvent` is also an option. However I don't know if there is a gdb notification that you can translate to `allThreadsContinued`

**Comment by asimgunes** [comment]
@jonahgraham , from the description below, I am assuming to receive running,thread-id="all" if all threads are continued.

> "The thread field can be the global thread ID of the thread that is now running, and it can be ‘all’ if all threads are running."

**Comment by jonahgraham** [comment]
@asimgunes yes, I think that is generated in the "all-stop" case, but in the "non-stop" case you are probably working on, I don't know if `all` is generated ever.

**Comment by asimgunes** [comment]
Hi @jonahgraham,

I checked the the conditions from the logs. They are compatible with the notes in the documentation and your expectation above. Let me write down some details here, thus, we can clearly state the runtime behaviour.

"all-stop" mode (gdbNonStop=false): Adapter is receiving `thread-id="all"` instead of the id of the continued thread, which is expected since all threads resumed in continue command. 

In single-thread environment: 

```
[09:43:19.223 UTC] GDB command: 0 -gdb-set non-stop off
...
[09:43:19.261 UTC] GDB command: 10 -exec-continue --thread 1
[09:43:19.261 UTC] GDB result: 10 running
[09:43:19.261 UTC] GDB exec async: running,thread-id="all"
```

In multi-thread environment: 

```
[09:43:19.554 UTC] GDB command: 0 -gdb-set non-stop off
...
[09:43:19.609 UTC] GDB command: 14 -exec-continue --thread 3
[09:43:19.609 UTC] GDB result: 14 running
[09:43:19.609 UTC] GDB exec async: running,thread-id="all"
```


"non-stop" mode (gdbNonStop=true): Adapter is receiving id of the resumed thread as the `thread-id`. In my test cases, I couldn't find a scenario that is sending thread-id="all" in non-stop mode.

In single-thread environment: 

```
[09:44:00.244 UTC] GDB command: 1 -gdb-set non-stop on
...
[09:44:00.281 UTC] GDB command: 11 -exec-continue --thread 1
[09:44:00.281 UTC] GDB result: 11 running
[09:44:00.281 UTC] GDB exec async: running,thread-id="1"
```

In multi-thread environment: 

```
[09:44:00.609 UTC] GDB command: 1 -gdb-set non-stop on
...
[09:44:00.677 UTC] GDB command: 18 -exec-continue --thread 3
[09:44:00.677 UTC] GDB result: 18 running
[09:44:00.677 UTC] GDB exec async: running,thread-id="3"
```

**Comment by jonahgraham** [comment]
Thanks @asimgunes for this contribution.
