### ISSUE TITLE
Implementation of evaluate request

### ISSUE THREAD

**Issue by simark** [eclipse-cdt-cloud/cdt-gdb-adapter#47]
I looked at the implementation of the `evaluate` request (specifically the `repl` context), and have some concerns.  My understanding is that the goal of this request is to evaluate an expression in the language you are debugging, and not executing debugger commands.  In a REPL such as the browser console, you input expressions that can be evaluated as javascript (such as `1 + 2`), and the debugger returns the result.

The current implementation executes the expression as a debugger command, which is not the same thing.  My understanding is that this allows to get a really basic gdb console in VSCode, leveraging the debugger console.

I think it would be very useful to let clients evaluate expressions in the language being debugged (e.g. `&myArray`) and return the result.  This would map pretty much directly to `-data-evaluate-expression` in GDB.

If it's still needed to run arbitrary GDB commands, we could add another context, but keep repl for evaluating C/C++ expressions.  In the long run, it will be much better to have an actual GDB console (#30) anyway.

Comments?

**Comment by simark** [comment]
Have you started to look into how to create custom views in VSCode?  Would it be possible to instantiate a separate console view/widget (like the repl), and customize it to send the request with a different `context`?

**Comment by dschaefer** [comment]
Yeah, we've done a bunch of custom webviews and such. And we'll do custom views for Registers and something with memory. I want to check out the Terminal API to see if we can do it there.

I also want to check out how the PlatformIO IDE does this stuff. Love to get those guys to switch to our extensions. We can at least learn from them. It's a pretty rich environment on VS code.

**Comment by dwjbosman** [comment]
I am trying to use the cdt-gdb-adapter as part of theia's cdt-gdb-vscode plugin. I can open Theia's debug console and interact with GDB. I think evaluateRequest in GDBDebugSession.js is called when a command is typed in the debug console. 

Unfortunately all commands send to evaluateRequest seem to be  handled as evaluation of variable expressions. So it is not possible to execute arbitrary GDB commands. In the  following issue https://github.com/microsoft/vscode-cpptools/issues/106 they describe using "-exec" when executing GDB commands. 

Is there any way of executing GDB commands directly?

**Comment by marechal-p** [comment]
If you are working on Linux, you can set the `openGdbConsole` configuration option to `true` in order to open a proper GDB prompt in a terminal. From there you should be able to use regular commands.

**Comment by dwjbosman** [comment]
The worked great!

**Comment by jonahgraham** [comment]
This was resolved in #69 - if there is follow-on work, new issues that explain what is left should be raised.
