### ISSUE TITLE
Support multi-location breakpoint

### ISSUE THREAD

**Issue by simark** [eclipse-cdt-cloud/cdt-gdb-adapter#64]
We will need to support multi-location breakpoints at some point.  A multi-location breakpoint can easily be creating a function-name breakpoint on a function that has two overloads:

```cpp
void hello(int i) {
}
void hello(double d) {
}
```

See this issue for adding multi-location breakpoints support in the protocol spec:
https://github.com/Microsoft/debug-adapter-protocol/issues/13

There is also a bug in the MI output by GDB when dealing with multi-location breakpoints, there is a patch here:
https://sourceware.org/ml/gdb-patches/2019-01/threads.html#00233

But even if it gets merged we will have to deal with the broken output when using older GDBs.

**Comment by jonahgraham** [comment]
Until there is changes in the DAP not sure what cdt-gdb-adapter can really do here. As new versions of DAP are released we should adapt cdt-gdb-adapter to take advantage of those improvements.

> But even if it gets merged we will have to deal with the broken output when using older GDBs.

For this part we can support only mi3 perhaps, but most of the work of dealing with broken output was done already in breakpoints.ts  as part of #154. https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/c653a9afaecf2063501ba02d0f438eea6925f468/src/mi/breakpoint.ts#L51-L67
