### ISSUE TITLE
use the bindings library to load the pty.node file.

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt-cloud/cdt-gdb-adapter#85]
The binding library provides an enhanced search path for loading *.node files. Then we can move it around without having to change the TypeScript code.

I'll start a CQ (approval for run-time usage) so we can use it. Won't take long.

**Comment by dschaefer** [comment]
Whoops, I meant bindings. Here https://www.npmjs.com/package/bindings

**Comment by dschaefer** [comment]
Use of the bindings library has been approved, CQ 18977 for members who have access. It's getting to be an automated process these days assuming the library has it's licensing files in place.

**Comment by jonahgraham** [comment]
This old issue may need to be revisited once/if there is a concrete problem we are having. The bindings package is very heavily used, but not updated in 4 years itself, so it may be that there is a more "modern" way of handling this issue.

As for the CQ aspect, the way approvals of third party IP is done has changed a lot too using the [dash license](https://github.com/eclipse/dash-licenses) tool
