### ISSUE TITLE
Support multiple versions of gdb.

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt-cloud/cdt-gdb-adapter#92]
There is a big change between 7.11 and 7.12 that enables newer gdb's to run in async mode making it easier for the adapter to control the inferior. However, we probably still need to support older gdb's.

CDT does this by detecting the version before starting up and then creating the proper stack for the version of gdb. We'll need to do the same here.

**Comment by dschaefer** [comment]
For whatever reason, CDT only started using exec-interrupt in 7.12. If we can talk away all the classes like GDBRunControl_7_12, then we don't need this. But there are lots of them.

**Comment by jonahgraham** [comment]
Since this issue was raised we had to add support to older versions of GDB, e.g. https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/188
