### ISSUE TITLE
Pause doesn't work on gdb 7.9.1

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt-cloud/cdt-gdb-adapter#98]
I've seen gdb 7.9 still floating around. The new Pause handing of sending gdb a SIGINT isn't working properly and seems to be ignored. Or it recently started working properly in gdb 7.12.

**Comment by jonahgraham** [comment]
This now works in general, with the exception of case covered in #99, see #194 for when the work was done, especially pause.spec.ts which only skips the test under these conditions;

https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/c8015bc29ee5aea8432d7c186b49d5336c20aeb8/src/integration-tests/pause.spec.ts#L33-L36
